replicaCount: 1

image:
  repository: silverdeath366/incident-backend
  pullPolicy: Always
  tag: latest

service:
  type: NodePort
  port: 8000

containerPort: 8000

env:
  - name: ENV
    value: "local"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false
